name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Android Tests
        uses: reactivecircus/android-emulator-runner@v2.28.0
        with:
          api-level: 30
          script: ./gradlew connectedDebugAndroidTest

      - name: Upload a Build Artifact
        if: ${{always()}}
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: android-test-reports
          # A file, directory or wildcard pattern that describes what to upload
          path: "**/build/reports/androidTests"
