name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          disable-animations: true
          force-avd-creation: false
          ram-size: 4096M
          emulator-boot-timeout: 12000
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-snapshot-save
          script: ./gradlew connectedDebugAndroidTest

#      - name: Upload a Build Artifact
#        if: ${{always()}}
#        uses: actions/upload-artifact@v3.1.2
#        with:
#          # Artifact name
#          name: android-test-reports
#          # A file, directory or wildcard pattern that describes what to upload
#          path: "**/build/reports/androidTests"
